api_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6ODA2MjQwNzg2NSwiaWF0IjoxNzU1MjA3ODY1LCJqdGkiOiIwODNmMmRmYTc4MGY0NTFmOWNjZjkyNTE4MGE1NjQ1YyIsInVzZXJfaWQiOjF9.slCHsfj8CFTmdNGmJ48FBfeFi9B0GmAJVfVmtWpnZNQ"
model_name: "yolov8s.pt"
project_name: "yolo_proj"
upload_as_annotations: True
host_local_storage_path: '/yolo/'