services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - ./label-studio-data:/label-studio/data
      - ./tasks:/label-studio/files
    environment:
      - LABEL_STUDIO_HOST=http://localhost:8080
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files
      - LABEL_STUDIO_PASSWORD=12345
      - LABEL_STUDIO_USERNAME=default_user@localhost
    restart: unless-stopped

  yolo-env:
    build: ./yolo_auto_label
    container_name: yolo-env
    volumes:
      - ./yolo_auto_label:/yolo_auto_label
      - ./models:/models
      - ./tasks:/tasks
      - ./logs:/logs
    working_dir: /yolo_auto_label
    command: tail -f /dev/null


