services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    volumes:
      - ./label-studio-data:/label-studio/data
      - ./tasks:/label-studio/files
    environment:
      - LABEL_STUDIO_HOST=http://localhost:8080
      - LABEL_STUDIO_LOCAL_FILES_SERVING_ENABLED=true
      - LABEL_STUDIO_LOCAL_FILES_DOCUMENT_ROOT=/label-studio/files
      - LABEL_STUDIO_PASSWORD=12345
      - LABEL_STUDIO_USERNAME=default_user@localhost
    restart: unless-stopped

  prefect-server:
    container_name: test-prefect-server
    image: prefecthq/prefect:3.4.8-python3.12
    environment:
     PREFECT_SERVER_API_HOST: 0.0.0.0
    command: prefect server start
    ports:
     - "4200:4200"

  prefect-worker:
    container_name: test-prefect-worker
    image: prefecthq/prefect:3.4.8-python3.12
    volumes:
     - ../src/prefect_flows:/app/src/prefect_flows/
     - ../label_studio_files:/label_studio/files
    depends_on:
     - prefect-server
    environment:
     PREFECT_API_URL: http://prefect-server:4200/api
     command: >
       bash -c "
         prefect work-pool create --set-as-default --type process default-agent-pool
         prefect deploy --prefect-file /app/src/prefect_flows/prefect.yaml --all
         prefect worker start --pool default-agent-pool --type process
       "
   
